### ISSUE TITLE
digestive-functors-blaze-0.6.0.6 does not build with digestive-functors-0.8.1.0

### ISSUE THREAD

**Issue by juhp** [jaspervdj/digestive-functors#132] opened 2016-08-21 13:59 UTC
Due to `fieldInputFile` type change?

Ditto for digestive-functors-lucid

**Comment by asakeron** [comment] 2016-09-06 05:15
digestive-functors-blaze seems to work fine since https://github.com/jaspervdj/digestive-functors/commit/64e8bce9407ec840fd82c09b8c4d119e78989a0b.

As for digestive-functors-lucid I submitted a PR https://github.com/athanclark/digestive-functors-lucid/pull/2 which fixes the problem.

**Comment by amigalemming** [comment] 2016-09-22 11:31
I had the same problem. The result type of `Text.Digestive.View.fieldInputFile` changed  from `Maybe FilePath` in `digestive-functors-0.8.0` to `[FilePath]` in `0.8.1`. This violates the PVP.

**Comment by asakeron** [comment] 2016-09-23 17:02
@amigalemming: I compared `digestive-functors-blaze` from Hackage and this repository and noticed they are different even though they have the same version:

```
$ cabal get digestive-functors-blaze-0.6.0.6
$ git clone digestive-functors
$ diff digestive-functors-blaze-0.6.0.6 digestive-functors/digestive-functors-blaze 
```
```diff
<     ! A.value (H.toValue value)
145,146c144
<     ref'  = absoluteRef ref view
<     value = fromMaybe "" $ fieldInputFile ref view
---
>     ref' = absoluteRef ref view
```
From the output above it's clear the problem you have is fixed in the repository but not uploaded to Hackage. I suppose @jaspervdj would not mind uploading the correct version.

**Comment by amigalemming** [comment] 2016-09-23 17:09
The above fix might make `digestive-functors-blaze` compatible with both 0.8.0 and 0.8.1 of `digestive-functors`. Nonetheless, 0.8.1 breaks the PVP and thus all other packages that rely on the `fieldInputFile` type of 0.8.0 will fail with 0.8.1 and vice versa. Thus, there is no other solution than relabeling `digestive-functors-0.8.1` to 0.9.

**Comment by asakeron** [comment] 2016-09-23 17:16
You are right, @amigalemming, both things need to be done.

**Comment by cimmanon** [comment] 2016-10-18 14:52
I'm the one who made the PR to change File to take a list rather than a Maybe.

It was intended to be a non-breaking change, so I can see why the maintainers chose the next version number the way they did.  Any library for rendering Views that does not compile due to expecting a Maybe from File is likely generating invalid HTML:  file inputs are not allowed to have a value attribute at all.  There's no reason to be poking around for this information when rendering a View.

**Comment by jaspervdj** [comment] 2016-10-31 10:04
I've bumped the version on Hackage to `digestive-functors-blaze-0.6.1.0`.  Thanks for reporting this and sorry for the delay!

**Closed by jaspervdj** 2016-10-31 10:04 UTC
